name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:    # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to enable proper merging

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git || echo "Upstream remote already exists"

      - name: Fetch upstream repository
        run: git fetch upstream

      - name: Merge upstream changes with conflict resolution
        run: |
          # Merge upstream/main into the current branch (master) using the "ours" strategy option
          # This ensures that if any conflicts occur, your fork’s version is favored
          git merge upstream/main -X ours --no-edit || true

      - name: Push merged changes to fork
        run: git push origin HEAD:main
